services:
  db:
    image: postgres:15
    container_name: feedback_tech
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedback_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:	
      - fase4net
networks:
  fase4net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
