quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DATABASE_USER}
quarkus.datasource.password=${DATABASE_PASSWORD}
quarkus.datasource.jdbc.url=${DATABASE_URL}

sqs.queue.url=${SQS_QUEUE_URL}

aws.region=${REGION_AWS}
quarkus.sqs.aws.region=${REGION_SQS}
quarkus.sqs.aws.credentials.type=default

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.http.host=0.0.0.0
quarkus.http.port=8081
